version: 2
project_name: peyk

builds:
  - id: peyk
    main: .
    binary: peyk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "peyk_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github-native

release:
  draft: false
  prerelease: auto
