package project

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const generatedMarker = "# Generated by peyk"

// EnsureDockerfile writes a framework-appropriate Dockerfile into the release
// directory unless the repository ships its own. Dockerfiles peyk generated
// earlier (identified by their marker line) are regenerated, so manifest
// changes like a new PHP version take effect on redeploy.
func (p *Project) EnsureDockerfile(releaseDir string) error {
	path := filepath.Join(releaseDir, "Dockerfile")
	if b, err := os.ReadFile(path); err == nil {
		if !strings.HasPrefix(string(b), generatedMarker) {
			return nil // project brings its own
		}
	}
	var content string
	switch p.Framework {
	case Laravel:
		content = p.laravelDockerfile()
	case NextJS:
		content = p.nextDockerfile()
	default:
		content = p.staticDockerfile()
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// laravelDockerfile builds on serversideup/php: production-hardened PHP-FPM +
// nginx in one container, runs as www-data, serves on :8080, /up healthy.
func (p *Project) laravelDockerfile() string {
	extLine := ""
	if len(p.PHPExtensions) > 0 {
		// serversideup images bundle mlocati's install-php-extensions helper.
		extLine = "RUN install-php-extensions " + strings.Join(p.PHPExtensions, " ") + "\n"
	}
	return fmt.Sprintf(`%s — regenerated on each deploy; ship your own Dockerfile to override.
FROM serversideup/php:%s-fpm-nginx AS base

ENV PHP_OPCACHE_ENABLE=1 \
    AUTORUN_ENABLED=false \
    HEALTHCHECK_PATH=%s

USER root
%s
# Build frontend assets when a package.json exists.
RUN if command -v node >/dev/null 2>&1; then true; else \
      curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
      apt-get install -y nodejs && apt-get clean; fi

COPY --chown=www-data:www-data composer.json composer.lock* /var/www/html/
USER www-data
RUN composer install --no-dev --no-interaction --prefer-dist --no-scripts --no-autoloader

COPY --chown=www-data:www-data . /var/www/html
RUN composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader && \
    if [ -f package.json ]; then npm ci && npm run build && rm -rf node_modules; fi
`, generatedMarker, p.PHPVersion, p.HealthPath, extLine)
}

// nextDockerfile is a standard multi-stage standalone build.
func (p *Project) nextDockerfile() string {
	return fmt.Sprintf(`# Generated by peyk — delete only if the repo ships its own Dockerfile.
FROM node:%s-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --frozen-lockfile; \
    elif [ -f yarn.lock ]; then corepack enable && yarn install --frozen-lockfile; \
    else npm ci; fi

FROM node:%s-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:%s-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=%d HOSTNAME=0.0.0.0
RUN addgroup -S app && adduser -S app -G app
COPY --from=builder --chown=app:app /app/.next/standalone ./
COPY --from=builder --chown=app:app /app/.next/static ./.next/static
COPY --from=builder --chown=app:app /app/public* ./public
USER app
EXPOSE %d
CMD ["node", "server.js"]
`, p.NodeVersion, p.NodeVersion, p.NodeVersion, p.Port, p.Port)
}

func (p *Project) staticDockerfile() string {
	return fmt.Sprintf(`# Generated by peyk — serves the repo root as static files.
FROM caddy:2-alpine
COPY . /srv
EXPOSE %d
CMD ["caddy", "file-server", "--root", "/srv", "--listen", ":%d"]
`, p.Port, p.Port)
}
